"""switch to db-stored photos

Revision ID: 22ce251d10cc
Revises: 09c040f9aae5
Create Date: 2026-09-13 20:13:42.157332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ce251d10cc'
down_revision = '09c040f9aae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_mimetype', sa.String(length=50), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_mimetype')
        batch_op.drop_column('photo_data')

    # ### end Alembic commands ###
